<?php require('parts/header.php'); ?>
<body class="theme--dark">
    <?php require('parts/preloader.php'); ?>
    <div id="page" class="page">
        <?php require('parts/navbar.php'); ?>
        <section class="inner-page-breadcrumb">
            <div class="container position-relative z-index-1 pt-4 pt-md-0">
                <div class="row g-4 g-xxl-5">
                    <div class="col-lg-8 col-xl-6">
                        <div class="d-none d-lg-flex position-relative mb-0">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb breadcrumb-dots pb-0 mb-2">
                                    <li class="breadcrumb-item">
                                        <a class="text-light" href="/">Home</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">Terms of Use</li>
                                </ol>
                            </nav>
                        </div>
                        <h1 class="title-breadcrumb">Terms of Use</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="inner-page-fullwidth pb-50">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <article>
                            <div class="article-wrapper">
                                <h3>General terms and conditions</h3>
                                <p>These terms and conditions constitute a legally binding agreement made between you, whether personally or on behalf of an entity (you), and neoslab.com, located at London (United Kingdom) (we, us), concerning your access to and use of the NeosLab website as well as any related websites and/or applications.</p>
                                <p>You agree that by accessing the site and/or services, you have read, understood, and agree to be bound by all of these terms and conditions.</p>
                                <p>If you do not agree with all of these terms and conditions, then you are prohibited from using the site and services and you must discontinue use immediately. We recommend that you print a copy of these terms and conditions for future reference.</p>
                                <p>The supplemental policies set out in section below, as well as any supplemental terms and condition or documents that may be posted on the site from time to time, are expressly incorporated by reference. We may make changes to these terms and conditions at any time. The updated version of these terms and conditions will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible.</p>
                                <p>You are responsible for reviewing these terms and conditions to stay informed of updates. Your continued use of the site represents that you have accepted such changes. We may update or change the site from time to time to reflect changes to our products, our users' needs and/or our business priorities.</p>
                                <p>The information provided on the site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. The site is intended for users who are at least 18 years old. If you are under the age of 18, you are not permitted to register for the site or use the services without parental permission.</p>
                                <h3>Acceptable use</h3>
                                <p>You may not access or use the site for any purpose other than that for which we make the site and our services available. The site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.</p>
                                <p>As a user of this site, you agree not to:</p>
                                <ul>
                                    <li>Systematically retrieve data or other content from the site to a compile database or directory without written permission from us.</li>
                                    <li>Make any unauthorized use of the site, including collecting usernames and/or email addresses of users to send unsolicited email or creating user accounts under false pretenses.</li>
                                    <li>Use a buying agent or purchasing agent to make purchases on the site.</li>
                                    <li>Use the site to advertise or sell goods and services.</li>
                                    <li>Circumvent, disable, or otherwise interfere with security-related features of the site, including features that prevent or restrict the use or copying of any content or enforce limitations on the use.</li>
                                    <li>Engage in unauthorized framing of or linking to the site.</li>
                                    <li>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
                                    <li>Make improper use of our support services, or submit false reports of abuse or misconduct.</li>
                                    <li>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
                                    <li>Advertise products or services not intended by us.</li>
                                    <li>Misrepresent experience, skills, or information about a user.</li>
                                    <li>Threaten users with negative feedback or offering services solely to give positive feedback to users.</li>
                                    <li>Disparage, tarnish, or otherwise harm, in our opinion, us and/or the site.</li>
                                    <li>Use, launch, or engage in any automated use of the system, such as using scripts to send comments or messages, robots, scrapers, offline readers, or similar data gathering and extraction tools.</li>
                                    <li>Use the site in a manner inconsistent with any applicable laws or regulations.</li>
                                    <li>Upload or transmit viruses, trojan horses, or other material that interferes with any party's uninterrupted use and enjoyment of the site.</li>
                                    <li>Copy or adapt the site's software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</li>
                                    <li>Harass, annoy, intimidate, or threaten any of our employees, agents, or other users.</li>
                                    <li>Attempt to access any portions of the site that you are restricted from accessing.</li>
                                    <li>Delete the copyright or other proprietary rights notice from any of the content.</li>
                                    <li>Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the site.</li>
                                    <li>Use the site or our content as part of any effort to compete with us or to create a revenue-generating endeavor or commercial enterprise.</li>
                                    <li>Use any information obtained from the site in order to harass, abuse, or harm another person.</li>
                                    <li>Attempt to impersonate another user or person, or use the username of another user.</li>
                                    <li>Interfere with, disrupt, or create an undue burden on the site or the networks and services connected to the site.</li>
                                    <li>Sell or otherwise transfer your profile.</li>
                                    <li>Falsely imply a relationship with us or another company with whom you do not have a relationship.</li>
                                </ul>
                                <h3>Information you provide to us</h3>
                                <p>You represent and warrant that all registration information you submit will be true, accurate, current, and complete and relate to you and not a third party. You will maintain the accuracy of such information and promptly update such information as necessary. You will keep your password confidential and will be responsible for all use of your password and account. You have the legal capacity and you agree to comply with these terms and conditions and you are not a minor in the jurisdiction in which you reside, or if a minor, you have received parental permission to use the site.</p>
                                <p>If you know or suspect that anyone other than you knows your user information and/or password you must promptly notify us. If you provide any information that is untrue, inaccurate, not current or incomplete, we may suspend or terminate your account. We may remove or change a user name you select if we determine that such user name is inappropriate.</p>
                                <p>As part of the functionality of the site, you may link your account with online accounts you may have with third party service providers by either providing your third party account login information through the site or allowing us to access your third party account, as is permitted under the applicable terms and conditions that govern your use of each third party account.</p>
                                <p>You represent that you are entitled to disclose your third party account login information to us and/or grant us access to your third party account without breach by you of any of the terms and conditions that govern your use of the applicable third party account and without obligating us to pay any fees or making us subject to any usage limitations imposed by such third party service providers.</p>
                                <p>By granting us access to any third party accounts, you understand that we may access, make available and store any content that you have provided to and stored in your third party account so that it is available on and through the site via your account, including without limitation any friend lists and we may submit and receive additional information to your third party account to the extent you are notified when you link your account with the third party account.</p>
                                <p>Depending on the third party accounts you choose and subject to the privacy settings that you have set in such third party accounts, personally identifiable information that you post to your third party accounts may be available on and through your account on the site. Please note that if a third party account or associated service becomes unavailable or our access to such third party account is terminated by the third party service provider, then Social Network content may no longer be available on and through the site.</p>
                                <p>You will have the ability to disable the connection between your account on the site and your third party accounts at any time. Please note that your relationship with the third party service providers associated with your third party accounts is governed solely by your agreement(s) with such third party service providers. We make no effort to review any social network content for any purpose, including but not limited to, for accuracy, legality or non-infringement, and we are not responsible for any social network content.</p>
                                <p>You acknowledge and agree that we may access your email address book associated with a third party account and your contacts list stored on your mobile device or tablet computer solely for purposes of identifying and informing you of those contacts who have also registered to use the site. At your email request to NeosLab or through your account settings (if applicable), we will deactivate the connection between the site and your third party account and attempt to delete any information stored on our servers that was obtained through such third party account, except the username and profile picture that became associated with your account.</p>
                                <h3>Your content</h3>
                                <p>There may be opportunities for you to post content to the site or send feedback to us. You understand and agree that your user content may be viewed by other users on the site, and that they may be able to see who has posted that user content.</p>
                                <p>You further agree that we can use your user content for any other purposes whatsoever in perpetuity without payment to you, and combine your user content with other content for use within the site and otherwise. We do not have to attribute your user content to you.</p>
                                <p>In posting user content, including reviews or making contact with other users of the site you shall comply with our <a href="/privacy-policy/">privacy policy</a>. You warrant that any user content does comply with our privacy policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. </p>
                                <p>We have the right to remove any user content you put on the site if, in our opinion, such user content does not comply with our terms and conditions. We are not responsible and accept no liability for any user content including any such content that contains incorrect information or is defamatory or loss of user content. We accept no obligation to screen, edit or monitor any user content but we reserve the right to remove, screen and/or edit any user content without notice and at any time user content has not been verified or approved by us and the views expressed by other users on the site do not represent our views or values.</p>
                                <h3>Our content</h3>
                                <p>Unless otherwise indicated, the site and services including source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the site are owned or licensed to us, and are protected by copyright and trade mark laws.</p>
                                <p>Except as expressly provided in these terms and conditions, no part of the site, services or our content may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</p>
                                <p>Provided that you are eligible to use the site, you are granted a limited license to access and use the site and Our content and to download or print a copy of any portion of the content to which you have properly gained access solely for your personal, non-commercial use.</p>
                                <p>You shall not try to gain unauthorized access to the site or any networks, servers or computer systems connected to the site and/or make for any purpose including error correction, any modifications, adaptions, additions or enhancements to the site or Our content, including the modification of the paper or digital copies you may have downloaded.</p>
                                <p>We shall prepare the site and our content with reasonable skill and care and use industry standard virus detection software to try to block the uploading of content to the site that contains viruses. The content on the site is provided for general information only. It is not intended to amount to advice on which you should rely. You must obtain professional or specialist advice before taking, or refraining from taking, any action on the basis of the content on the site.</p>
                                <p>Although we make reasonable efforts to update the information on our site, we make no representations, warranties or guarantees, whether express or implied, that Our content on the site is accurate, complete or up to date.</p>
                                <h3>How we deal with copyright issues</h3>
                                <p>We comply with the Digital Millennium Copyright Act. To learn more about how we deal with claims of copyright infringement. The Digital Millennium Copyright Act lays out a system of legal requirements for dealing with allegations of copyright infringement. NeosLab complies with the DMCA, and we respond to notices of alleged infringement if they comply with the law and the requirements set forth in our copyright policy.</p>
                                <h3>Link to third party content</h3>
                                <p>The site may contain links to websites or applications operated by third parties. We do not have any influence or control over any such third party websites or applications or the third party operator. We are not responsible for and do not endorse any third party websites or applications or their availability or content.</p>
                                <p>We accept no responsibility for adverts contained within the site. If you agree to purchase goods and/or services from any third party who advertises in the site, you do so at your own risk. The advertiser, and not us, is responsible for such goods and/or services and if you have any questions or complaints in relation to them, you should contact the advertiser.</p>
                                <h3>Site management</h3>
                                <p>We reserve the right at our sole discretion, to monitor the site for breaches of these terms and conditions, take appropriate legal action against anyone in breach of applicable laws or these terms and conditions, refuse, restrict access to or availability of, or disable any of your contributions, remove from the site or otherwise disable all files and content that are excessive in size or are in any way a burden to our systems and otherwise manage the site in a manner designed to protect our rights and property and to facilitate the proper functioning of the site and services.</p>
                                <p>We do not guarantee that the site will be secure or free from bugs or viruses. You are responsible for configuring your information technology, computer programs and platform to access the site and you should use your own virus protection software.</p>
                                <h3>Modifications to and availability of the site</h3>
                                <p>We reserve the right to change, modify, or remove the contents of the site at any time or for any reason at our sole discretion without notice. We also reserve the right to modify or discontinue all or part of the services without notice at any time. We cannot guarantee the site and services will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the site, resulting in interruptions, delays, or errors.</p>
                                <p>You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the site or services during any downtime or discontinuance of the site or services. We are not obliged to maintain and support the site or services or to supply any corrections, updates, or releases.</p>
                                <p>There may be information on the site that contains typographical errors, inaccuracies, or omissions that may relate to the services, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information at any time, without prior notice.</p>
                                <h3>Disclaimer/limitation of liability</h3>
                                <p>The site and services are provided on an as-is and as-available basis. You agree that your use of the site and/or services will be at your sole risk except as expressly set out in these terms and conditions. All warranties, terms, conditions and undertakings, express or implied in connection with the site and services and your use thereof including, without limitation, the implied warranties of satisfactory quality, fitness for a particular purpose and non-infringement are excluded to the fullest extent permitted by applicable law.</p>
                                <p>We make no warranties or representations about the accuracy or completeness of the site's content and are not liable for any errors or omissions in content, any unauthorized access to or use of our servers and/or any and all personal information and/or financial information stored on our server, any interruption or cessation of transmission to or from the site or services and/or any bugs, viruses, trojan horses, or the like which may be transmitted to or through the site by any third party. We will not be responsible for any delay or failure to comply with our obligations under these terms and conditions if such delay or failure is caused by an event beyond our reasonable control.</p>
                                <h3>Term and termination</h3>
                                <p>These terms and conditions shall remain in full force and effect while you use the site or services or are otherwise a user of the site, as applicable. You may terminate your use or participation at any time, for any reason, by following the instructions for terminating user accounts in your account settings, if available, or by <a href="/contact/">contacting us</a>. </p>
                                <p>Without limiting any other provision of these terms and conditions, we reserve the right to, in our sole discretion and without notice or liability, deny access to and use of the site and the services (including blocking certain IP addresses), to any person for any reason including without limitation for breach of any representation, warranty or covenant contained in these terms and conditions or of any applicable law or regulation.</p>
                                <p>If we determine, in our sole discretion, that your use of the site/services is in breach of these terms and conditions or of any applicable law or regulation, we may terminate your use or participation in the site and the services or delete your profile and any content or information that you posted at any time, without warning, in our sole discretion.</p>
                                <p>If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>
                                <h3>Mobile application</h3>
                                <p>If you access the services via a mobile application, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the mobile application on wireless electronic devices owned or controlled by you, and to access and use the mobile application on such devices strictly in accordance with the terms and conditions of this license.</p>
                                <p>As a user of the application, you agree not to:</p>
                                <ul>
                                    <li>Reverse engineer, explore or otherwise try to discover the source code of the software/application unless you have first written to us requesting interoperability information and we have failed to provide you with that information or if we have failed to offer to provide you with interoperability information on reasonable conditions.</li>
                                    <li>Make any modification, adaptation, improvement, enhancement, translation or derivative work from the application.</li>
                                    <li>Breach any applicable laws, rules or regulations in connection with your access or use of the application.</li>
                                    <li>Remove, alter or obscure any proprietary notice including any notice of copyright or trade mark posted by us.</li>
                                    <li>Use the application for any revenue generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended.</li>
                                    <li>Make the application available over a network or other environment permitting access or use by multiple devices or users at the same time.</li>
                                    <li>Use the application for creating a product, service or software that is, directly or indirectly, competitive with or in any way a substitute for the application.</li>
                                    <li>Use the application to send automated queries to any website or to send any unsolicited commercial e-mail or use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing or distribution of any applications, accessories or devices for use with the application.</li>
                                </ul>
                                <p>The following terms apply when you use a mobile application obtained from either the Apple Store or Google Play to access the services:</p>
                                <ul>
                                    <li>The license granted to you for our mobile application is limited to a non-transferable license to use the application on a device that utilizes the Apple iOS or Android operating system, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor terms of service.</li>
                                    <li>We are responsible for providing any maintenance and support services with respect to the mobile application as specified in these terms and conditions or as otherwise required under applicable law. You acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the mobile application.</li>
                                    <li>In the event of any failure of the mobile application to conform to any applicable warranty, you may notify an App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the mobile application, and to the maximum extent permitted by applicable law, an App Distributor will have no other warranty obligation whatsoever with respect to the mobile application.</li>
                                    <li>You represent and warrant that you are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a “terrorist supporting” country and you are not listed on any U.S. government list of prohibited or restricted parties.</li>
                                    <li>You acknowledge and agree that the App Distributors are third party beneficiaries of these terms and conditions, and that each App Distributor will have the right to enforce these terms and conditions against you as a third party beneficiary thereof.</li>
                                </ul>
                                <h3>General</h3>
                                <p>Visiting the site, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the site, satisfy any legal requirement that such communication be in writing.</p>
                                <p>You hereby agree to the use of electronic signatures, contracts, orders and other records and to electronic delivery of notices, policies and records of transactions initiated or completed by us or via the site. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by other than electronic means.</p>
                                <p>These terms and conditions and any policies or operating rules posted by us on the site or in respect to the services constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these terms and conditions shall not operate as a waiver of such right or provision. We may assign any or all of our rights and obligations to others at any time.</p>
                                <p>Except as stated under the mobile application section, a person who is not a party to these terms and conditions shall have no right under the contracts to enforce any term of these terms and conditions. In order to resolve a complaint regarding the services or to receive further information regarding use of the services, please <a href="/contact/">contact us</a>. </p>
                                <h3>Dispute resolution and governing law</h3>
                                <p>We're located in London (United Kingdom), and any disputes with us have to be handled in London (United Kingdom) under London (United Kingdom) law. We at NeosLab encourage you to <a href="/contact/">contact us</a> if you're having an issue, before resorting to the courts. In the unfortunate situation where legal action does arise, these Terms (and all other rules, policies, or guidelines incorporated by reference) will be governed by and construed in accordance with the laws of London (United Kingdom), without giving effect to any principles of conflicts of law, and without application of the Uniform Computer Information Transaction Act or the United Nations Convention of Controls for International Sale of Goods. </p>
                                <p>You agree that NeosLab and its services are deemed a passive website that does not give rise to jurisdiction over NeosLab or its parents, subsidiaries, affiliates, assigns, employees, agents, directors, officers, or shareholders, either specific or general, in any jurisdiction other than the London (United Kingdom). You agree that any action at law or in equity arising out of or relating to these Terms, or your use or non-use of NeosLab, shall be filed only in the state or federal courts located in London (United Kingdom) County, and you hereby consent and submit to the personal jurisdiction of these courts for the purposes of litigating any such action. You hereby irrevocably waive any right you may have to trial by jury in any dispute, action, or proceeding.</p>
                                <h3>The rest</h3>
                                <p>These Terms and the other material referenced in them are the entire agreement between you and NeosLab with respect to the services. They supersede all other communications and proposals (whether oral, written, or electronic) between you and NeosLab with respect to the services and govern our future relationship. If any provision of these terms is found to be invalid under the law, that provision will be limited or eliminated to the minimum extent necessary so that the Terms otherwise will remain in full force and effect and enforceable. The failure of either you or NeosLab to exercise any right provided for in these Terms in any way won't be deemed a waiver of any other rights.</p>
                                <p>These Terms are personal to you. You can't assign them, transfer them, or sub-license them unless you get NeosLab's prior written consent. NeosLab has the right to assign, transfer, or delegate any of its rights and obligations under these Terms without your consent. NeosLab will provide you notice via email, written notice, or by conspicuously posting the notice on our Site.</p>
                                <hr>
                                <p>
                                    <strong>Latest revised:</strong> June 14th, 2026
                                </p>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </section>
        <?php require('parts/cta.php'); ?>
        <?php require('parts/footer.php'); ?>
        <?php require('parts/scripts.php'); ?>
</body>
</html>